
trigger:
  branches:
    include: [main, devops]

pool:
  name: MyPool

variables:
  acrName:       quarkstech     # quarkstech.azurecr.io/image:tag
  acrConnection: acreshan      
  imageTag:      $(Build.BuildId)           

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '24.x'

- task: PowerShell@2
  inputs:
    filePath: scripts/build.ps1

- task: Docker@2
  displayName: Build Backend Image
  inputs:
    command: buildAndPush
    repository: backend
    dockerfile: backend/Dockerfile
    containerRegistry: $(acrConnection)
    tags: |
      $(imageTag)

- task: Docker@2
  displayName: Build Frontend Image
  inputs:
    command: buildAndPush
    repository: frontend
    dockerfile: frontend/Dockerfile
    containerRegistry: $(acrConnection)
    tags: |
      $(imageTag)