trigger:
  branches:
    include:
      - main
      - develop
 
pool:
  name: MyPool
 

variables:
  dockerUser: eshukla
  frontendVersion: v1
  backendVersion: v1

stages:
  - stage: Frontend
    displayName: Frontend — build, test, push
    jobs:
    - job: FrontendJob
      steps:
 
      - script: npm install
        workingDirectory: frontend
        displayName: Install frontend deps
 
      - task: Docker@2
        displayName: Build and push frontend image
        inputs:
          containerRegistry: DockerHubConnection
          repository: $(dockerUser)/nexus-frontend
          command: buildAndPush
          dockerfile: frontend/Dockerfile
          buildContext: frontend
          tags: |
            $(frontendVersion).$(Build.BuildId)
            $(frontendVersion)

  - stage: Backend
    displayName: Backend — build, test, push
    dependsOn: []    
    jobs:
    - job: BackendJob
      steps:
 
      - script: npm install
        workingDirectory: backend
        displayName: Install backend deps
 
      - task: Docker@2
        displayName: Build and push backend image
        inputs:
          containerRegistry: DockerHubConnection
          repository: $(dockerUser)/nexus-backend
          command: buildAndPush
          dockerfile: backend/Dockerfile
          buildContext: backend
          tags: |
            $(backendVersion).$(Build.BuildId)
            $(backendVersion)